/**
 * This code was generated by Builder.io.
 */
import React from "react";

function ConversionsChart() {
  return (
    <div className="flex flex-col flex-1 shrink px-3 basis-0 max-w-[1558px] min-w-[240px] max-md:max-w-full">
      <div className="flex flex-col justify-center w-full bg-white rounded-xl shadow-sm max-md:max-w-full">
        <div className="flex flex-col flex-1 px-3 py-6 w-full max-md:max-w-full">
          <h3 className="w-full text-base font-semibold leading-none whitespace-nowrap text-slate-700 max-md:max-w-full">
            Conversions
          </h3>
          <div className="flex flex-col items-center w-full text-sm text-center min-h-[10px] text-slate-700 max-md:max-w-full">
            <div className="flex flex-col justify-center max-w-full min-h-[276px] w-[447px]">
              <div className="flex flex-col items-center px-11 pt-16 pb-7 w-full max-md:px-5">
                <div className="flex flex-col max-w-full w-[170px]">
                  <div className="flex shrink-0 h-40" />
                  <div className="self-center mt-3">Returning Customer</div>
                </div>
              </div>
            </div>
          </div>
          <div className="flex flex-wrap pt-6 w-full text-center min-h-[107px] max-md:max-w-full">
            <div className="flex flex-col flex-1 shrink px-3 basis-0 max-w-[471px]">
              <div className="px-20 w-full text-sm text-slate-500 max-md:px-5">
                This Week
              </div>
              <div className="px-20 pb-px mt-3 w-full text-2xl font-semibold leading-none whitespace-nowrap text-slate-700 max-md:px-5">
                23.5k
              </div>
            </div>
            <div className="flex flex-col flex-1 shrink px-3 basis-0 max-w-[471px]">
              <div className="px-20 w-full text-sm text-slate-500 max-md:px-5">
                Last Week
              </div>
              <div className="px-16 pb-px mt-3 w-full text-2xl font-semibold leading-none whitespace-nowrap text-slate-700 max-md:px-5">
                41.05k
              </div>
            </div>
          </div>
          <div className="flex flex-col justify-center items-center pt-3 w-full text-sm text-center text-zinc-700 max-md:max-w-full">
            <button className="self-stretch px-48 py-2.5 max-w-full rounded-xl border border-solid bg-slate-100 border-slate-100 w-[447px] max-md:px-5">
              View Details
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

export default ConversionsChart;
