/**
 * This code was generated by Builder.io.
 */
import React from "react";
import StatCard from "./StatCard";
import PerformanceChart from "./PerformanceChart";
import ConversionsChart from "./ConversionsChart";
import SessionsByCountry from "./SessionsByCountry";
import TopPages from "./TopPages";
import RecentOrders from "./RecentOrders";

function Dashboard() {
  const statCards = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/1cfb38954afd2510b288ec25de6fcfcdce3588ac51a105791b25a7ad7f3d9e37?placeholderIfAbsent=true&apiKey=5dee21b4f50742c9b5c16494a624cb30",
      title: "Total Orders",
      value: "13, 647",
      change: "2.3%",
      changeType: "increase",
      period: "Last Week",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/454a3a04ee2fb1d659d1823e38a005a50a541ee0dadf01d10076e2f5ce3fc558?placeholderIfAbsent=true&apiKey=5dee21b4f50742c9b5c16494a624cb30",
      title: "Deals Product claimed",
      value: "9, 526",
      change: "8.1%",
      changeType: "increase",
      period: "Last Month",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/e95074f43e8b1b9285a190bc8b4d01997eb2e93d1c2a497188319d772f92905e?placeholderIfAbsent=true&apiKey=5dee21b4f50742c9b5c16494a624cb30",
      title: "Deals",
      value: "976",
      change: "0.3%",
      changeType: "decrease",
      period: "Last Month",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/89495e21d82d818b6b3d0785167d355bf3c2aa885db878c96bb0f093464da5a6?placeholderIfAbsent=true&apiKey=5dee21b4f50742c9b5c16494a624cb30",
      title: "Profits",
      value: "Rs.123.6k",
      change: "10.6%",
      changeType: "decrease",
      period: "Last Month",
    },
  ];

  return (
    <div className="flex flex-col grow shrink max-w-[1558px] min-w-[240px] w-[1558px] max-md:max-w-full">
      <div className="flex flex-col px-3 text-sm text-amber-900 min-h-[69px] max-md:max-w-full">
        <div className="overflow-hidden px-5 py-3 w-full bg-orange-100 rounded-xl max-md:max-w-full">
          We regret to inform you that our server is currently experiencing
          technical difficulties.
        </div>
      </div>
      <div className="flex flex-wrap w-full max-md:max-w-full">
        {statCards.map((card, index) => (
          <StatCard key={index} {...card} />
        ))}
      </div>
      <div className="flex flex-wrap w-full min-h-[489px] max-md:max-w-full">
        <PerformanceChart />
        <ConversionsChart />
        <SessionsByCountry />
      </div>
      <div className="flex flex-wrap justify-center w-full min-h-[545px] max-md:max-w-full">
        <TopPages />
        <RecentOrders />
      </div>
    </div>
  );
}

export default Dashboard;
