/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Footer() {
  return (
    <footer className="flex absolute inset-x-0 bottom-0 z-0 justify-center items-center px-14 py-5 w-full text-sm text-center shadow-sm bg-white bg-opacity-0 h-[60px] min-h-[60px] text-slate-400 max-md:px-5">
      <div className="flex flex-col flex-1 shrink self-stretch my-auto w-full basis-0 max-w-[1558px] min-w-[240px] max-md:max-w-full">
        <div className="flex flex-wrap justify-center w-full max-md:max-w-full">
          <div className="flex flex-wrap flex-1 shrink justify-center items-start basis-0 max-w-[1535px] min-w-[240px] px-[655px] size-full max-md:px-5 max-md:max-w-full">
            <div className="grow shrink w-[159px]">
              2024 © Khaitan India Ltd.
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
}

export default Footer;
