/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SearchBar from "./SearchBar";
import IconButton from "./IconButton";

function Header() {
  return (
    <header className="flex flex-col pr-14 pl-80 w-full bg-stone-50 min-h-[100px] max-md:px-5 max-md:max-w-full">
      <div className="flex flex-wrap gap-10 justify-between items-center w-full max-md:max-w-full">
        <div className="flex justify-center items-center self-stretch py-8 my-auto text-lg font-bold leading-none uppercase whitespace-nowrap min-h-[100px] text-slate-500">
          <div className="self-stretch p-2 my-auto rounded-[36px]">
            Welcome!
          </div>
        </div>
        <div className="flex flex-wrap gap-1.5 items-center self-stretch my-auto min-w-[240px] max-md:max-w-full">
          <IconButton
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/e7a4d23f75d694cb6119982cbd2624e226b9d1c0c512e0d920d7b03d99b5c312?placeholderIfAbsent=true&apiKey=5dee21b4f50742c9b5c16494a624cb30"
            alt="Notification icon"
          />
          <IconButton
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/0d5f12e77c5efac9bb6a9c64fa3194d2e6706f3791552fd92a6ce60c5ceb3e01?placeholderIfAbsent=true&apiKey=5dee21b4f50742c9b5c16494a624cb30"
            alt="Message icon"
          />
          <IconButton
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/295e90806a9e6f37074298697963c35c2cf180dc0162eeb99747bbd93b4a2fcf?placeholderIfAbsent=true&apiKey=5dee21b4f50742c9b5c16494a624cb30"
            alt="Settings icon"
          />
          <IconButton
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/d92737cf06a626b00db5588a9ffb505ee4523c80fa32e6f6f77c78fa158755b8?placeholderIfAbsent=true&apiKey=5dee21b4f50742c9b5c16494a624cb30"
            alt="User profile icon"
          />
          <SearchBar />
        </div>
      </div>
    </header>
  );
}

export default Header;
