/**
 * This code was generated by Builder.io.
 */
import React from "react";

function IconButton({ src, alt }) {
  return (
    <button className="flex justify-center items-center self-stretch py-8 my-auto w-10 min-h-[100px]">
      <div className="flex flex-col justify-center items-center self-stretch p-2 my-auto w-10 rounded-3xl">
        <div className="flex items-start w-6">
          <img
            loading="lazy"
            src={src}
            alt={alt}
            className="object-contain w-6 aspect-square"
          />
        </div>
      </div>
    </button>
  );
}

export default IconButton;
