/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Sidebar from "./Sidebar";
import Footer from "./Footer";

function Layout({ children }) {
  return (
    <div className="flex relative flex-col justify-center bg-[linear-gradient(0deg,#F9F7F7_0%,#F9F7F7_100%,#FFF)]">
      <Header />
      <div className="flex z-0 flex-col flex-1 w-full max-md:max-w-full">
        <div className="flex relative flex-col self-end px-10 pb-16 max-w-full min-h-[1100px] w-[1657px] max-md:px-5">
          <Sidebar />
          <main className="ml-[280px]">{children}</main>
        </div>
      </div>
      <Footer />
    </div>
  );
}

export default Layout;
