/**
 * This code was generated by Builder.io.
 */
import React from "react";

function RecentOrders() {
  const orders = [
    {
      id: "#RB5625",
      date: "08 Sept 2024",
      product:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/9ac4e4131cdb2b4b526b1edb2d91c97806e7d0faf4124670c1a41ba5f7666595?placeholderIfAbsent=true&apiKey=5dee21b4f50742c9b5c16494a624cb30",
      customer: "Aayush Kumar",
      email: "kumar.aayush@mail.com",
      phone: "+91 1234567890",
      address: "abc def street",
      payment: "Credit Card",
      status: "Accepted",
    },
    {
      id: "#RB9652",
      date: "08 Sept 2024",
      product:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/ee4d05e601640c1a3235ec5c12562ff7275e70c2193b95066aaf4de01bbe5f75?placeholderIfAbsent=true&apiKey=5dee21b4f50742c9b5c16494a624cb30",
      customer: "Aakash Agrawal",
      email: "agrawal.aakash.com",
      phone: "+91 1234567890",
      address: "abc def street",
      payment: "Credit Card",
      status: "Delivered",
    },
    {
      id: "#RB5984",
      date: "08 Sept 2024",
      product:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/fc896ed82633983c68d3bc46f15488b4446164815f07468a6c8dd537a351908a?placeholderIfAbsent=true&apiKey=5dee21b4f50742c9b5c16494a624cb30",
      customer: "Peter T. Smith",
      email: "peter.smith@mail.com",
      phone: "+91 1234567890",
      address: "abc def street",
      payment: "COD",
      status: "In transit",
    },
    {
      id: "#RB3625",
      date: "08 Sept 2024",
      product:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/e2b891c20e5136baf70b9ce38139a8dddc5900ce57615c8bc5067cb67c0328c4?placeholderIfAbsent=true&apiKey=5dee21b4f50742c9b5c16494a624cb30",
      customer: "Shivam Kasera",
      email: "kasera.shivam@mail.com",
      phone: "+91 1234567890",
      address: "abc def street",
      payment: "Debit Card",
      status: "Cancelled",
    },
    {
      id: "#RB5984",
      date: "08 Sept 2024",
      product:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/fbc312c2b15df876c11f5e2e65c288736c103c1cb54adacaea2b171fe8c7397f?placeholderIfAbsent=true&apiKey=5dee21b4f50742c9b5c16494a624cb30",
      customer: "Peter T. Smith",
      email: "peter.smith@mail.com",
      phone: "+91 1234567890",
      address: "abc def street",
      payment: "COD",
      status: "Accepted",
    },
  ];

  return (
    <div className="flex flex-col flex-1 shrink px-3 w-full basis-0 max-w-[1558px] min-w-[240px] max-md:max-w-full">
      <div className="flex flex-col w-full bg-white rounded-xl shadow-sm max-md:max-w-full">
        <div className="flex flex-col flex-1 justify-center p-6 w-full max-md:px-5 max-md:max-w-full">
          <div className="flex flex-wrap gap-10 justify-between items-center w-full max-md:max-w-full">
            <h3 className="self-stretch my-auto text-base font-semibold leading-none text-slate-700">
              Recent Orders
            </h3>
            <button className="flex gap-2 justify-center self-stretch px-3.5 py-2.5 my-auto rounded-lg bg-orange-500 bg-opacity-10 w-[116px]">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/e1e05ede70704e16c846250fe3db6d68700fdf393a52d3a2f1eb36eb952fc47b?placeholderIfAbsent=true&apiKey=5dee21b4f50742c9b5c16494a624cb30"
                alt=""
                className="object-contain w-3 aspect-[0.92]"
              />
              <span className="my-auto text-sm text-center text-orange-500">
                Create Order
              </span>
            </button>
          </div>
        </div>
        <div className="flex overflow-hidden flex-col w-full max-md:max-w-full">
          <div className="flex flex-col text-sm font-bold bg-slate-100 bg-opacity-50 text-slate-500 max-md:max-w-full">
            <div className="flex flex-wrap items-center max-md:max-w-full">
              <div className="self-stretch pt-3.5 pr-10 pb-4 pl-6 my-auto border-b border-solid border-b-slate-200 max-md:px-5">
                Order ID.
              </div>
              <div className="self-stretch pt-3.5 pr-24 pb-4 pl-3.5 my-auto whitespace-nowrap border-b border-solid border-b-slate-200 max-md:pr-5">
                Date
              </div>
              <div className="self-stretch pt-3.5 pr-9 pb-4 pl-3.5 my-auto whitespace-nowrap border-b border-solid border-b-slate-200 max-md:pr-5">
                Product
              </div>
              <div className="self-stretch pt-3.5 pr-20 pb-4 pl-3.5 my-auto border-b border-solid border-b-slate-200 max-md:pr-5">
                Customer Name
              </div>
              <div className="self-stretch pt-3.5 pr-48 pb-4 pl-3.5 my-auto border-b border-solid border-b-slate-200 min-w-[240px] max-md:pr-5">
                Email ID
              </div>
              <div className="self-stretch pt-3.5 pr-32 pb-4 pl-3.5 my-auto border-b border-solid border-b-slate-200 max-md:pr-5">
                Phone No.
              </div>
              <div className="self-stretch pt-3.5 pr-32 pb-4 pl-3.5 my-auto whitespace-nowrap border-b border-solid border-b-slate-200 max-md:pr-5">
                Address
              </div>
              <div className="self-stretch pt-3.5 pr-12 pb-4 pl-3.5 my-auto border-b border-solid border-b-slate-200 max-md:pr-5">
                Payment Type
              </div>
              <div className="self-stretch pt-3.5 pr-24 pb-4 pl-3.5 my-auto whitespace-nowrap border-b border-solid border-b-slate-200 max-md:pr-5">
                Status
              </div>
            </div>
          </div>
          <div className="flex flex-col w-full max-w-[1521px] max-md:max-w-full">
            {orders.map((order, index) => (
              <div
                key={index}
                className="flex flex-wrap items-center max-md:max-w-full"
              >
                <div className="flex flex-col items-start self-stretch pt-5 pr-11 pb-6 pl-6 my-auto text-sm whitespace-nowrap border-b border-solid border-b-slate-200 text-slate-400 max-md:px-5">
                  <div>{order.id}</div>
                </div>
                <div className="self-stretch pt-5 pr-12 pb-6 pl-3.5 my-auto text-sm border-b border-solid border-b-slate-200 text-slate-500 max-md:pr-5">
                  {order.date}
                </div>
                <div className="flex flex-col justify-center items-start self-stretch pt-3.5 pr-14 pb-4 pl-3.5 my-auto border-b border-solid border-b-slate-200 max-md:pr-5">
                  <img
                    loading="lazy"
                    src={order.product}
                    alt="Product"
                    className="object-contain w-9 aspect-square"
                  />
                </div>
                <div className="flex flex-col items-start self-stretch pt-5 pr-24 pb-6 pl-3.5 my-auto text-sm border-b border-solid border-b-slate-200 text-slate-400 max-md:pr-5">
                  <div>{order.customer}</div>
                </div>
                <div className="self-stretch pt-5 pr-24 pb-6 pl-3.5 my-auto text-sm whitespace-nowrap border-b border-solid border-b-slate-200 min-w-[240px] text-slate-500 w-[262px] max-md:pr-5">
                  {order.email}
                </div>
                <div className="self-stretch pt-5 pr-16 pb-6 pl-3.5 my-auto text-sm border-b border-solid border-b-slate-200 text-slate-500 max-md:pr-5">
                  {order.phone}
                </div>
                <div className="self-stretch pt-5 pr-20 pb-6 pl-3.5 my-auto text-sm border-b border-solid border-b-slate-200 text-slate-500 max-md:pr-5">
                  {order.address}
                </div>
                <div className="self-stretch pt-5 pr-20 pb-6 pl-3.5 my-auto text-sm border-b border-solid border-b-slate-200 text-slate-500 w-[163px] max-md:pr-5">
                  {order.payment}
                </div>
                <div className="flex gap-1.5 self-stretch px-3.5 py-6 my-auto border-b border-solid border-b-slate-200 w-[149px]">
                  <div className="flex items-start self-start">
                    <img
                      loading="lazy"
                      src={`http://b.io/ext_${
                        order.status === "Accepted"
                          ? "19"
                          : order.status === "Delivered"
                          ? "21"
                          : order.status === "In transit"
                          ? "23"
                          : "25"
                      }-`}
                      alt=""
                      className="object-contain w-3.5 aspect-square"
                    />
                  </div>
                  <div className="text-sm basis-auto text-slate-500">
                    {order.status}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
        <div className="flex flex-col justify-center px-3 pb-5 w-full border-t border-solid border-t-slate-200 max-md:max-w-full">
          <div className="flex z-10 flex-wrap mt-0">
            <div className="flex flex-col flex-1 shrink justify-center pt-6 text-sm leading-5 basis-0 max-w-[1510px] min-w-[240px] text-slate-500 max-md:max-w-full">
              <div className="flex flex-col px-3 w-full max-w-[1510px] min-h-[35px] max-md:max-w-full">
                <div className="w-full max-md:max-w-full">
                  <span className="text-slate-500">Showing </span>
                  <span className="font-bold text-slate-500">5</span>
                  <span className="text-slate-500"> of </span>
                  <span className="font-bold text-slate-500"> 99,999 </span>
                  <span className="text-slate-500"> orders</span>
                </div>
              </div>
            </div>
            <div className="flex flex-col justify-center pt-6 max-w-[1510px] w-[205px]">
              <div className="flex flex-col px-3 w-full max-w-[205px] min-h-[35px]">
                <div className="flex gap-0 w-full">
                  <button className="flex flex-col w-10">
                    <div className="flex flex-col justify-center px-3.5 pt-3 pb-2.5 w-full bg-white rounded-xl border border-solid border-slate-200">
                      <div className="flex items-start w-full">
                        <img
                          loading="lazy"
                          src="https://cdn.builder.io/api/v1/image/assets/TEMP/0ea4b43f73cd94841a9eb7118f43124ca8a7aa4cdca420f26d59b5420db3e3df?placeholderIfAbsent=true&apiKey=5dee21b4f50742c9b5c16494a624cb30"
                          alt="Previous page"
                          className="object-contain w-3.5 aspect-square"
                        />
                      </div>
                    </div>
                  </button>
                  <button className="flex flex-col text-sm text-white whitespace-nowrap w-[35px]">
                    <div className="px-3.5 bg-orange-500 border border-orange-500 border-solid h-[35px] w-[35px]">
                      1
                    </div>
                  </button>
                  <button className="flex flex-col text-sm text-gray-600 whitespace-nowrap w-[35px]">
                    <div className="px-3.5 bg-white border border-solid border-slate-200 h-[35px] w-[35px]">
                      2
                    </div>
                  </button>
                  <button className="flex flex-col text-sm text-gray-600 whitespace-nowrap w-[35px]">
                    <div className="px-3.5 bg-white border border-solid border-slate-200 h-[35px] w-[35px]">
                      3
                    </div>
                  </button>
                  <button className="flex flex-col w-10">
                    <div className="flex flex-col justify-center px-3.5 pt-3 pb-2.5 w-full bg-white rounded-none border border-solid border-slate-200">
                      <div className="flex items-start w-full">
                        <img
                          loading="lazy"
                          src="https://cdn.builder.io/api/v1/image/assets/TEMP/87eb97735631cc83832463c8ff11a93db3c77606dd547304492fbd6616455aeb?placeholderIfAbsent=true&apiKey=5dee21b4f50742c9b5c16494a624cb30"
                          alt="Next page"
                          className="object-contain w-3.5 aspect-square"
                        />
                      </div>
                    </div>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default RecentOrders;
