/**
 * This code was generated by Builder.io.
 */
import React from "react";

function SearchBar() {
  return (
    <div className="flex flex-col self-stretch pl-3 my-auto min-w-[240px] w-[244px]">
      <div className="flex flex-col max-w-full w-[232px]">
        <div className="flex relative flex-col w-full">
          <input
            type="search"
            placeholder="Search..."
            aria-label="Search"
            className="flex z-0 flex-col justify-center px-6 py-3.5 w-full text-sm whitespace-nowrap rounded-lg bg-stone-200 text-slate-500 max-md:px-5"
          />
          <div className="flex absolute inset-y-3 z-0 flex-col left-[11px] right-[203px] w-[18px]">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/df87c59764d836a4eb335f779af0f842107265b95827f67e3c4f9d0f3c16c347?placeholderIfAbsent=true&apiKey=5dee21b4f50742c9b5c16494a624cb30"
              alt=""
              className="object-contain w-full aspect-square"
            />
          </div>
        </div>
      </div>
    </div>
  );
}

export default SearchBar;
