/**
 * This code was generated by Builder.io.
 */
import React from "react";

function SessionsByCountry() {
  return (
    <div className="flex flex-col flex-1 shrink px-3 basis-0 max-w-[1558px] min-w-[240px] max-md:max-w-full">
      <div className="flex flex-col justify-center w-full bg-white rounded-xl shadow-sm max-md:max-w-full">
        <div className="flex flex-col flex-1 px-3 py-6 w-full max-md:max-w-full">
          <h3 className="w-full text-base font-semibold leading-none text-slate-700 max-md:max-w-full">
            Sessions by Country
          </h3>
          <div className="flex overflow-hidden flex-col justify-center items-start w-full text-sm min-h-[316px] text-slate-500 max-md:max-w-full">
            <div className="flex flex-col justify-center py-12 max-w-full w-[447px]">
              <div className="flex relative flex-col gap-1 items-start px-11 py-12 w-full min-h-[218px] max-md:px-5 max-md:max-w-full">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/84bdb7463dc705ea821cdec4f6e88222d2de9d203af67add43b2035296dee063?placeholderIfAbsent=true&apiKey=5dee21b4f50742c9b5c16494a624cb30"
                  alt="World map"
                  className="object-cover absolute inset-0 size-full"
                />
                <div className="flex relative flex-col grow shrink-0 items-start py-1 pr-14 pl-5 aspect-[2.319] basis-0 w-fit max-md:pr-5">
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/178f0b9f076f51b9407f2564dc828f8cbc3a1330500395c8d60a04c6fcaebaf0?placeholderIfAbsent=true&apiKey=5dee21b4f50742c9b5c16494a624cb30"
                    alt=""
                    className="object-cover absolute inset-0 size-full"
                  />
                  <div className="relative">Canada</div>
                  <div className="relative mt-3.5 ml-3.5 max-md:ml-2.5">
                    United States
                  </div>
                  <div className="relative self-center mt-12 max-md:mt-10">
                    Brazil
                  </div>
                </div>
                <div className="flex relative flex-col whitespace-nowrap">
                  <div>Russia</div>
                  <div className="self-start mt-6">China</div>
                </div>
              </div>
            </div>
          </div>
          <div className="flex flex-wrap w-full text-center min-h-[83px] max-md:max-w-full">
            <div className="flex flex-col flex-1 shrink px-3 basis-0 max-w-[471px]">
              <div className="px-20 w-full text-sm text-slate-500 max-md:px-5">
                This Week
              </div>
              <div className="px-20 pb-px mt-3 w-full text-2xl font-semibold leading-none whitespace-nowrap text-slate-700 max-md:px-5">
                23.5k
              </div>
            </div>
            <div className="flex flex-col flex-1 shrink px-3 basis-0 max-w-[471px]">
              <div className="px-20 w-full text-sm text-slate-500 max-md:px-5">
                Last Week
              </div>
              <div className="px-16 pb-px mt-3 w-full text-2xl font-semibold leading-none whitespace-nowrap text-slate-700 max-md:px-5">
                41.05k
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default SessionsByCountry;
