/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SidebarItem from "./SidebarItem";

function SidebarSection({ title, items }) {
  return (
    <section className="flex flex-col w-full">
      <h2 className="px-8 py-2.5 w-full text-xs font-bold tracking-wide text-gray-400 uppercase whitespace-nowrap min-h-[36px] max-md:px-5">
        {title}
      </h2>
      {items.map((item, index) => (
        <SidebarItem key={index} {...item} />
      ))}
    </section>
  );
}

export default SidebarSection;
