/**
 * This code was generated by Builder.io.
 */
import React from "react";

function StatCard({ icon, title, value, change, changeType, period }) {
  return (
    <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow px-3 min-h-[173px]">
        <div className="flex overflow-hidden flex-col w-full bg-white rounded-xl shadow-sm">
          <div className="flex flex-col flex-1 justify-center px-3 py-6 w-full">
            <div className="flex flex-wrap w-full">
              <div className="flex flex-col flex-1 shrink items-start px-3 basis-0 max-w-[277px]">
                <div className="flex flex-col justify-center items-center w-14 h-14 rounded-xl bg-orange-500 bg-opacity-30 min-h-[56px]">
                  <div className="flex flex-1 justify-center items-center p-3 size-full">
                    <img
                      loading="lazy"
                      src={icon}
                      alt=""
                      className="object-contain flex-1 shrink self-stretch my-auto w-8 aspect-square basis-0"
                    />
                  </div>
                </div>
              </div>
              <div className="flex flex-col flex-1 shrink px-3 text-right basis-0 max-w-[277px]">
                <div className="overflow-hidden pl-9 w-full text-sm leading-5 text-slate-500 max-md:pl-5">
                  {title}
                </div>
                <div className="pb-px mt-1.5 w-full text-2xl font-semibold leading-none text-slate-700">
                  {value}
                </div>
              </div>
            </div>
          </div>
          <div className="flex flex-col justify-center px-6 py-3 w-full bg-slate-100 bg-opacity-50 max-md:px-5">
            <div className="flex gap-10 justify-between items-center w-full">
              <div className="flex gap-3.5 self-stretch py-1.5 my-auto w-[113px]">
                <div className="flex">
                  <div className="flex items-start">
                    <img
                      loading="lazy"
                      src={
                        changeType === "increase"
                          ? "https://cdn.builder.io/api/v1/image/assets/TEMP/d92f7272b87cf90d95a60b0e6afc79c71c00a534948224d254f3bde3b4d8dd5c?placeholderIfAbsent=true&apiKey=5dee21b4f50742c9b5c16494a624cb30"
                          : "https://cdn.builder.io/api/v1/image/assets/TEMP/7c79ad331a82cbc7005233961adc0d9fc28967032b9b3c964b4c7a05f2cb09db?placeholderIfAbsent=true&apiKey=5dee21b4f50742c9b5c16494a624cb30"
                      }
                      alt=""
                      className="object-contain w-3 aspect-square"
                    />
                  </div>
                  <div
                    className={`text-sm ${
                      changeType === "increase"
                        ? "text-green-500"
                        : "text-red-400"
                    }`}
                  >
                    {change}
                  </div>
                </div>
                <div className="text-xs text-slate-500">{period}</div>
              </div>
              <button className="self-stretch my-auto text-xs font-bold text-slate-500">
                View More
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default StatCard;
