/**
 * This code was generated by Builder.io.
 */
import React from "react";

function TopPages() {
  const pages = [
    {
      path: "Product/fans/fanType 1",
      views: 465,
      exitRate: 4.4,
      exitRateType: "increase",
    },
    {
      path: "Product/fans/fanTpe 1",
      views: 426,
      exitRate: 20.4,
      exitRateType: "decrease",
    },
    {
      path: "Product/fans/fa",
      views: 254,
      exitRate: 12.25,
      exitRateType: "neutral",
    },
    {
      path: "Khaitan/auth-login",
      views: 3369,
      exitRate: 5.2,
      exitRateType: "increase",
    },
    {
      path: "Khaitan/email.html",
      views: 985,
      exitRate: 64.2,
      exitRateType: "decrease",
    },
    {
      path: "Khaitan/careers",
      views: 653,
      exitRate: 2.4,
      exitRateType: "increase",
    },
    {
      path: "Khaitan/about-us",
      views: 478,
      exitRate: 1.4,
      exitRateType: "decrease",
    },
  ];

  return (
    <div className="flex flex-col flex-1 shrink px-3 basis-0 max-w-[1558px] min-w-[240px] max-md:max-w-full">
      <div className="flex flex-col w-full bg-white rounded-xl shadow-sm h-[465px] max-md:max-w-full">
        <div className="flex flex-wrap justify-between items-center px-6 pt-5 pb-5 w-full border-b border-solid border-b-slate-200 max-md:px-5 max-md:max-w-full">
          <h3 className="flex-1 shrink self-stretch my-auto text-base font-semibold leading-none basis-[26px] min-w-[240px] text-slate-700">
            Top Pages
          </h3>
          <button className="self-stretch px-3.5 py-2 my-auto text-sm text-center text-orange-500 rounded-lg bg-orange-500 bg-opacity-10">
            View All
          </button>
        </div>
        <div className="flex overflow-hidden flex-col w-full text-sm text-slate-500 max-md:max-w-full">
          <div className="flex flex-col font-bold bg-slate-100 bg-opacity-50 max-md:max-w-full">
            <div className="flex flex-wrap items-center max-md:max-w-full">
              <div className="self-stretch pt-3.5 pr-40 pb-4 pl-6 my-auto border-b border-solid border-b-slate-200 min-w-[240px] max-md:px-5">
                Page Path
              </div>
              <div className="self-stretch pt-3.5 pr-11 pb-4 pl-3.5 my-auto border-b border-solid border-b-slate-200 max-md:pr-5">
                Page Views
              </div>
              <div className="self-stretch pt-3.5 pr-10 pb-4 pl-3.5 my-auto border-b border-solid border-b-slate-200 max-md:pr-5">
                Exit Rate
              </div>
            </div>
          </div>
          <div className="flex flex-col max-md:max-w-full">
            {pages.map((page, index) => (
              <div
                key={index}
                className="flex flex-wrap items-center max-md:max-w-full"
              >
                <div className="flex flex-col items-start self-stretch pt-3.5 pr-16 pb-4 pl-6 my-auto border-b border-solid border-b-slate-200 min-w-[240px] max-md:px-5">
                  <div>{page.path}</div>
                </div>
                <div className="self-stretch pt-3.5 pr-24 pb-4 pl-3.5 my-auto whitespace-nowrap border-b border-solid border-b-slate-200 max-md:pr-5">
                  {page.views}
                </div>
                <div className="flex flex-col items-start self-stretch pt-4 pr-16 pb-4 pl-3.5 my-auto text-xs font-bold leading-none text-center whitespace-nowrap border-b border-solid border-b-slate-200 max-md:pr-5">
                  <div
                    className={`px-1.5 py-1 rounded ${
                      page.exitRateType === "increase"
                        ? "bg-green-500 bg-opacity-20 text-green-500"
                        : page.exitRateType === "decrease"
                        ? "bg-red-400 bg-opacity-20 text-red-400"
                        : "bg-amber-400 bg-opacity-20 text-amber-400"
                    }`}
                  >
                    {page.exitRate}%
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
        <div className="flex flex-col justify-center px-3 pb-5 w-full border-t border-solid border-t-slate-200 max-md:max-w-full">
          <div className="flex z-10 flex-wrap mt-0">
            <div className="flex flex-col flex-1 shrink justify-center pt-6 text-sm leading-5 basis-0 max-w-[1510px] min-w-[240px] text-slate-500 max-md:max-w-full">
              <div className="flex flex-col px-3 w-full max-w-[1510px] min-h-[35px] max-md:max-w-full">
                <div className="w-full max-md:max-w-full">
                  <span className="text-slate-500">Showing </span>
                  <span className="font-bold text-slate-500">5</span>
                  <span className="text-slate-500"> of </span>
                  <span className="font-bold text-slate-500"> 99,999 </span>
                  <span className="text-slate-500"> pages</span>
                </div>
              </div>
            </div>
            <div className="flex flex-col justify-center pt-6 max-w-[1510px] w-[205px]">
              <div className="flex flex-col px-3 w-full max-w-[205px] min-h-[35px]">
                <div className="flex gap-0 w-full">
                  <button className="flex flex-col w-10">
                    <div className="flex flex-col justify-center px-3.5 pt-3 pb-2.5 w-full bg-white rounded-xl border border-solid border-slate-200">
                      <div className="flex items-start w-full">
                        <img
                          loading="lazy"
                          src="https://cdn.builder.io/api/v1/image/assets/TEMP/0ea4b43f73cd94841a9eb7118f43124ca8a7aa4cdca420f26d59b5420db3e3df?placeholderIfAbsent=true&apiKey=5dee21b4f50742c9b5c16494a624cb30"
                          alt="Previous page"
                          className="object-contain w-3.5 aspect-square"
                        />
                      </div>
                    </div>
                  </button>
                  <button className="flex flex-col text-sm text-white whitespace-nowrap w-[35px]">
                    <div className="px-3.5 bg-orange-500 border border-orange-500 border-solid h-[35px] w-[35px]">
                      1
                    </div>
                  </button>
                  <button className="flex flex-col text-sm text-gray-600 whitespace-nowrap w-[35px]">
                    <div className="px-3.5 bg-white border border-solid border-slate-200 h-[35px] w-[35px]">
                      2
                    </div>
                  </button>
                  <button className="flex flex-col text-sm text-gray-600 whitespace-nowrap w-[35px]">
                    <div className="px-3.5 bg-white border border-solid border-slate-200 h-[35px] w-[35px]">
                      3
                    </div>
                  </button>
                  <button className="flex flex-col w-10">
                    <div className="flex flex-col justify-center px-3.5 pt-3 pb-2.5 w-full bg-white rounded-none border border-solid border-slate-200">
                      <div className="flex items-start w-full">
                        <img
                          loading="lazy"
                          src="https://cdn.builder.io/api/v1/image/assets/TEMP/87eb97735631cc83832463c8ff11a93db3c77606dd547304492fbd6616455aeb?placeholderIfAbsent=true&apiKey=5dee21b4f50742c9b5c16494a624cb30"
                          alt="Next page"
                          className="object-contain w-3.5 aspect-square"
                        />
                      </div>
                    </div>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default TopPages;
